[package]
name = "nix-cache-overlay"
version = "0.1.0"
edition = "2021"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]

[dependencies]
axum = "*"
axum-extra = { version = "*", features = ["typed-header"] }
http = "*"
hyper = "*"
hyper-tls = "*"
hyper-util = "*"
http-body-util = "*"
aws-config = { version = "*", features = ["behavior-version-latest"] }
aws-sigv4 = "*"
aws-credential-types = "*"
tracing = "*"
tracing-subscriber = "*"
tokio = { version = "*", features = ["rt-multi-thread"] }
clap = { version = "*", features = ["derive"] }
anyhow = "*"
thiserror = "*"
bytes = "*"
regex = "*"
constant_time_eq = "*"
